services:
  webhookd:
    image: ncarlier/webhookd
    container_name: webhookd
    hostname: webhookd
    networks:
      - admin
    volumes:
      - ./config/scripts:/scripts
      - /dev/fuse:/dev/fuse
    environment:
      - VIRTUAL_HOST=webhookd.admin.pknw1.co.uk
      - VIRTUAL_PORT=8080
      - APP_GROUP=Core
      - APP_LOGO=https://static-00.iconduck.com/assets.00/portainer-icon-1465x2048-t155ekm0.png
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M

networks:
  admin:
    external: true
